#=META
source:
  author: Bavithra
  coauthor: Claude Opus 5
  reviewer:
docstrings:
  author: Bavithra
  coauthor: Claude Opus 5
  reviewer:
refs:
credits: N/A
=#

"""
    Time

Abstract root of the time-evolution-direction tags used to parameterize [`Propagator`](@ref).
Concrete subtypes: [`RealTime`](@ref), [`ImaginaryTime`](@ref).
"""
abstract type Time end

"""
Real-time evolution: `Propagator{RealTime}` represents `exp(-i*dt*H)`. See [`Time`](@ref).
"""
struct RealTime <: Time end

"""
Imaginary-time evolution: `Propagator{ImaginaryTime}` represents `exp(-dt*H)` (used for ground-
state projection / thermal states). See [`Time`](@ref).
"""
struct ImaginaryTime <: Time end

"""
    Propagator{T<:Time}

The unitary (real-time) or non-unitary-but-projecting (imaginary-time) time-evolution operator
generated by a local [`Hamiltonian`](@ref), lazy in the same sense as [`Observable`](@ref) - not
yet materialized into any tensor network. `T` selects real vs. imaginary time evolution the same
way `ProductFormula`'s `Order` or `TensorTrain`'s `P` are plain type parameters dispatched on, not
runtime-inspected fields.

# Fields

  - `hamiltonian :: Hamiltonian` - the generator.
  - `dt          :: Float64`     - the (real- or imaginary-)time step.
"""
struct Propagator{T<:Time} <: AbstractProcess
    hamiltonian::Hamiltonian
    dt::Float64
end

function tensor(::Propagator)
    return error(
        "tensor(::Propagator) is not yet implemented - Propagator has no tensor representation yet",
    )
end
function outputs(::Propagator)
    return error(
        "outputs(::Propagator) is not yet implemented - Propagator has no tensor representation yet",
    )
end
function inputs(::Propagator)
    return error(
        "inputs(::Propagator) is not yet implemented - Propagator has no tensor representation yet",
    )
end

"""
    propagator(H::Hamiltonian, dt; kind::Type{<:Time}=RealTime) -> Propagator{kind}

The propagator `H` generates at timestep `dt` - named after what it produces (matching
[`identity_process`](@ref)/`to_mps`'s naming convention in this codebase), not a verb like
"generate" or "evolve" that would overclaim: `H` is the generator of time translations in the
infinitesimal sense (Stone's theorem), `exp(-iHt)`/`exp(-Ht)` is the actual propagator, and this
function still only produces the *lazy* [`Propagator`](@ref) wrapper - no exponentiation happens
here.
"""
function propagator(H::Hamiltonian, dt; kind::Type{<:Time}=RealTime)
    return Propagator{kind}(H, dt)
end

"""
    trotterize(propagator::Propagator, pf::ProductFormula)

Apply the product-formula splitting tagged by `pf` to `propagator`'s Hamiltonian, producing the
ordered `(term, coefficient)` gate-block recipe for one Trotter step (via `Subroutines.sequence`)

  - the TEBD gate sequence a [`Propagator`](@ref) reduces to under Trotterization. **Not yet
    implemented** - depends on [`Hamiltonian`](@ref) exposing a term decomposition, which doesn't
    exist yet.
"""
function trotterize(propagator::Propagator, pf::ProductFormula)
    return error(
        "trotterize is not yet implemented - depends on Hamiltonian exposing a term " *
        "decomposition, which doesn't exist yet",
    )
end
