name: Build docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/knottyanyon/qritical-docs:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure project activated and build docs
        run: |
          julia --project=docs -e 'using Pkg; Pkg.activate("docs"); Pkg.instantiate()'
          julia --project=docs docs/make.jl
